version: '3'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000
  agendash:
    build: .
    command:
      ./node_modules/.bin/agendash --db=mongodb://db/agenda --port 3001
    ports:
      - "3001:3001"
    links:
      - db
  db:
    image: mongo:3
    command: "--smallfiles"
    # command: "--smallfiles --logpath=/dev/null"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
